### ISSUE TITLE
Generation: "Unknown experiment" with vec2text_ffn_train.yaml

### ISSUE THREAD

**Issue by ondovb** [xingjian-zhang/map2text#19]
(map2text) MWC36G27YR6Y:map2text bdo8$ python map2text/quick_start.py map2text/configs/cs_research_idea/vec2text_ffn_train.yaml 
    Traceback (most recent call last):
      File "/Users/bdo8/Documents/Projects/LitVectors/map2text/map2text/quick_start.py", line 280, in <module>
        main()
      File "/Users/bdo8/Documents/Projects/LitVectors/map2text/map2text/quick_start.py", line 276, in main
        raise ValueError(f"Unknown experiment type: {experiment_type}.")
    ValueError: Unknown experiment type: training.

**Comment by xingjian-zhang** [comment]
@ondovb Thank you for bringing this issue. We did not use this method in the paper, so the code and documentation might be somewhat unclear. To train the model and save the weights, please run the following command:
```
python map2text/model/trainable_ffn/train.py map2text/configs/cs_research_context/vec2text_ffn_train.yaml 
```

And then run the inference code separately:
```
python map2text/quick_start.py map2text/configs/cs_research_context/vec2text_ffn_inference.yaml 
```

Reference: https://github.com/xingjian-zhang/map2text/blob/4b9744ae71ca25be234a892499bf8c8dab9e5e6e/map2text/configs/cs_research_context/vec2text_ffn_train.yaml#L1-L8
